language: nix
script: nix-shell --run 'make ci'
cache:
  directories:
  - .psc-package
  - output
before_deploy:
  - nix-shell --run '>packages.dhall dhall <<< ./src/packages.dhall'
deploy:
  provider: releases
  api_key: $RELEASE_KEY
  file:
    - packages.dhall
  skip_cleanup: true
  on:
    tags: true
